route:
  group_by: [ alertname ]
  receiver: 'mail' # default receiver
  repeat_interval: 24h
  
receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.ionos.es:587'
        auth_username: 'prueba@iesjoseplanes.es'
        auth_password: "LOS3cerditos"
        from: 'prueba@iesjoseplanes.es'
        to: 'fernandodomin.ruiz@murciaeduca.es'
        require_tls: true


